export type CelebrityReferenceSeed = {
  aliases?: string[];
  imageHash?: string | null;
  imageUrl?: string | null;
  name: string;
  region: string;
};

const northAmericaMusic = [
  "Taylor Swift",
  "Beyonce",
  "Rihanna",
  "Ariana Grande",
  "Billie Eilish",
  "Lady Gaga",
  "Madonna",
  "Britney Spears",
  "Miley Cyrus",
  "Selena Gomez",
  "Demi Lovato",
  "Olivia Rodrigo",
  "Sabrina Carpenter",
  "Doja Cat",
  "Nicki Minaj",
  "Cardi B",
  "Lizzo",
  "SZA",
  "Lana Del Rey",
  "Katy Perry",
  "Kesha",
  "Christina Aguilera",
  "Jennifer Lopez",
  "Mariah Carey",
  "Whitney Houston",
  "Tina Turner",
  "Janet Jackson",
  "Diana Ross",
  "Cher",
  "Alicia Keys",
  "Halsey",
  "Camila Cabello",
  "Shawn Mendes",
  "Justin Bieber",
  "Drake",
  "The Weeknd",
  "Post Malone",
  "Bruno Mars",
  "Usher",
  "Chris Brown",
  "Kanye West",
  "Ye",
  "Jay-Z",
  "Eminem",
  "Snoop Dogg",
  "Tupac Shakur",
  "Notorious B.I.G.",
  "Nas",
  "Kendrick Lamar",
  "J. Cole",
  "Travis Scott",
  "Tyler The Creator",
  "Lil Wayne",
  "Future",
  "Metro Boomin",
  "Playboi Carti",
  "ASAP Rocky",
  "Ice Spice",
  "Megan Thee Stallion",
  "Frank Ocean",
  "Pharrell Williams",
  "Prince",
  "Michael Jackson",
  "Elvis Presley",
  "Johnny Cash",
  "Dolly Parton",
  "Bob Dylan",
  "Bruce Springsteen",
  "Billy Joel",
  "Stevie Wonder",
  "Marvin Gaye",
  "Aretha Franklin",
  "Jimi Hendrix",
  "Kurt Cobain",
  "Dave Grohl",
  "Axl Rose",
  "Slash",
  "KISS",
  "Metallica",
  "Nirvana",
  "Guns N Roses",
  "Aerosmith",
  "Green Day",
  "Red Hot Chili Peppers",
  "Foo Fighters",
  "Linkin Park",
  "Blink-182",
  "Paramore",
  "My Chemical Romance",
  "Fall Out Boy",
  "Twenty One Pilots",
] as const;

const europeMusic = [
  "Dua Lipa",
  "Adele",
  "Harry Styles",
  "Ed Sheeran",
  "Elton John",
  "David Bowie",
  "Freddie Mercury",
  "George Michael",
  "Amy Winehouse",
  "Robbie Williams",
  "Sam Smith",
  "Lewis Capaldi",
  "Stormzy",
  "Central Cee",
  "Charli XCX",
  "Florence Welch",
  "Kate Bush",
  "Annie Lennox",
  "Mick Jagger",
  "Keith Richards",
  "Paul McCartney",
  "John Lennon",
  "Ringo Starr",
  "George Harrison",
  "Ozzy Osbourne",
  "Liam Gallagher",
  "Noel Gallagher",
  "Thom Yorke",
  "Robert Smith",
  "Bono",
  "The Edge",
  "Sting",
  "Phil Collins",
  "Peter Gabriel",
  "Eric Clapton",
  "Rod Stewart",
  "Sade",
  "Seal",
  "Spice Girls",
  "The Beatles",
  "The Rolling Stones",
  "Queen",
  "Pink Floyd",
  "Led Zeppelin",
  "Oasis",
  "Blur",
  "Radiohead",
  "Coldplay",
  "Arctic Monkeys",
  "The Cure",
  "Depeche Mode",
  "The Smiths",
  "ABBA",
  "Bjork",
  "Zara Larsson",
  "Avicii",
  "Swedish House Mafia",
  "Maneskin",
  "Andrea Bocelli",
  "Luciano Pavarotti",
  "Celine Dion",
] as const;

const filmAndTelevision = [
  "Marilyn Monroe",
  "Audrey Hepburn",
  "Charlie Chaplin",
  "James Dean",
  "Elizabeth Taylor",
  "Marlon Brando",
  "Al Pacino",
  "Robert De Niro",
  "Jack Nicholson",
  "Clint Eastwood",
  "Meryl Streep",
  "Tom Hanks",
  "Tom Cruise",
  "Brad Pitt",
  "Leonardo DiCaprio",
  "Johnny Depp",
  "Keanu Reeves",
  "Robert Downey Jr.",
  "Chris Evans",
  "Chris Hemsworth",
  "Chris Pratt",
  "Ryan Reynolds",
  "Ryan Gosling",
  "Dwayne Johnson",
  "Will Smith",
  "Samuel L. Jackson",
  "Morgan Freeman",
  "Denzel Washington",
  "Harrison Ford",
  "Arnold Schwarzenegger",
  "Sylvester Stallone",
  "Bruce Willis",
  "Nicolas Cage",
  "Jim Carrey",
  "Adam Sandler",
  "Ben Stiller",
  "Robin Williams",
  "Eddie Murphy",
  "Jamie Foxx",
  "Matthew McConaughey",
  "Joaquin Phoenix",
  "Heath Ledger",
  "Christian Bale",
  "Cillian Murphy",
  "Matt Damon",
  "Ben Affleck",
  "George Clooney",
  "Mark Wahlberg",
  "Jason Momoa",
  "Jason Statham",
  "Daniel Craig",
  "Pierce Brosnan",
  "Sean Connery",
  "Hugh Jackman",
  "Tom Hardy",
  "Idris Elba",
  "Benedict Cumberbatch",
  "Henry Cavill",
  "Andrew Garfield",
  "Tobey Maguire",
  "Tom Holland",
  "Pedro Pascal",
  "Oscar Isaac",
  "Timothee Chalamet",
  "Austin Butler",
  "Jacob Elordi",
  "Zendaya",
  "Margot Robbie",
  "Scarlett Johansson",
  "Angelina Jolie",
  "Jennifer Aniston",
  "Julia Roberts",
  "Sandra Bullock",
  "Nicole Kidman",
  "Charlize Theron",
  "Natalie Portman",
  "Anne Hathaway",
  "Emma Stone",
  "Emma Watson",
  "Jennifer Lawrence",
  "Gal Gadot",
  "Brie Larson",
  "Elizabeth Olsen",
  "Millie Bobby Brown",
  "Sydney Sweeney",
  "Jenna Ortega",
  "Florence Pugh",
  "Anya Taylor-Joy",
  "Aubrey Plaza",
  "Saoirse Ronan",
  "Cate Blanchett",
  "Kate Winslet",
  "Tilda Swinton",
  "Helena Bonham Carter",
  "Daniel Radcliffe",
  "Rupert Grint",
  "Ralph Fiennes",
  "Gary Oldman",
  "Anthony Hopkins",
  "Ian McKellen",
  "Patrick Stewart",
  "Ewan McGregor",
  "Liam Neeson",
  "Colin Farrell",
  "Michael Fassbender",
  "Viggo Mortensen",
  "Orlando Bloom",
  "Elijah Wood",
  "Robert Pattinson",
  "Kristen Stewart",
  "Vin Diesel",
  "Michelle Rodriguez",
  "Jackie Chan",
  "Jet Li",
  "Donnie Yen",
  "Bruce Lee",
  "Michelle Yeoh",
  "Chow Yun-fat",
  "Tony Leung",
  "Gong Li",
  "Zhang Ziyi",
  "Song Kang-ho",
  "Lee Jung-jae",
  "Bae Doona",
  "Mads Mikkelsen",
  "Javier Bardem",
  "Penelope Cruz",
  "Antonio Banderas",
  "Salma Hayek",
] as const;

const sportsStars = [
  "Michael Jordan",
  "Dennis Rodman",
  "Scottie Pippen",
  "Kobe Bryant",
  "LeBron James",
  "Stephen Curry",
  "Shaquille O'Neal",
  "Magic Johnson",
  "Larry Bird",
  "Kevin Durant",
  "Kyrie Irving",
  "Allen Iverson",
  "Dwyane Wade",
  "Carmelo Anthony",
  "James Harden",
  "Giannis Antetokounmpo",
  "Luka Doncic",
  "Nikola Jokic",
  "Victor Wembanyama",
  "Ja Morant",
  "Jayson Tatum",
  "Damian Lillard",
  "Anthony Davis",
  "Zion Williamson",
  "Caitlin Clark",
  "Serena Williams",
  "Venus Williams",
  "Naomi Osaka",
  "Coco Gauff",
  "Simone Biles",
  "Michael Phelps",
  "Usain Bolt",
  "Tiger Woods",
  "Tom Brady",
  "Patrick Mahomes",
  "Travis Kelce",
  "Aaron Rodgers",
  "Peyton Manning",
  "Joe Montana",
  "Odell Beckham Jr.",
  "Lionel Messi",
  "Cristiano Ronaldo",
  "Neymar",
  "Kylian Mbappe",
  "Erling Haaland",
  "Mohamed Salah",
  "Karim Benzema",
  "Robert Lewandowski",
  "Harry Kane",
  "David Beckham",
  "Zinedine Zidane",
  "Ronaldinho",
  "Ronaldo Nazario",
  "Pele",
  "Diego Maradona",
  "Zlatan Ibrahimovic",
  "Luka Modric",
  "Sergio Ramos",
  "Andres Iniesta",
  "Xavi Hernandez",
  "Iker Casillas",
  "Wayne Rooney",
  "Paul Pogba",
  "Antoine Griezmann",
  "Son Heung-min",
  "Sadio Mane",
  "Virgil van Dijk",
  "Alex Morgan",
  "Megan Rapinoe",
  "Mia Hamm",
  "Roger Federer",
  "Rafael Nadal",
  "Novak Djokovic",
  "Andy Murray",
  "Carlos Alcaraz",
  "Lewis Hamilton",
  "Max Verstappen",
  "Michael Schumacher",
  "Ayrton Senna",
  "Conor McGregor",
  "Khabib Nurmagomedov",
  "Mike Tyson",
  "Muhammad Ali",
  "Floyd Mayweather",
  "Manny Pacquiao",
  "John Cena",
  "Dwayne Wade",
  "Hulk Hogan",
  "Stone Cold Steve Austin",
  "The Undertaker",
  "Ronda Rousey",
] as const;

const fashionAndCulture = [
  "Kim Kardashian",
  "Kylie Jenner",
  "Kendall Jenner",
  "Kris Jenner",
  "Bella Hadid",
  "Gigi Hadid",
  "Hailey Bieber",
  "Cara Delevingne",
  "Naomi Campbell",
  "Kate Moss",
  "Tyra Banks",
  "Heidi Klum",
  "Karl Lagerfeld",
  "Virgil Abloh",
  "Alexander McQueen",
  "Vivienne Westwood",
  "Coco Chanel",
  "Andy Warhol",
  "Jean-Michel Basquiat",
  "Keith Haring",
  "Banksy",
  "Frida Kahlo",
  "Pablo Picasso",
  "Salvador Dali",
  "Vincent van Gogh",
  "Albert Einstein",
  "Steve Jobs",
  "Elon Musk",
  "Mark Zuckerberg",
  "Jeff Bezos",
  "Bill Gates",
  "Barack Obama",
  "Michelle Obama",
  "Donald Trump",
  "Joe Biden",
  "Princess Diana",
  "Queen Elizabeth II",
] as const;

const globalMusicAndGroups = [
  "Bad Bunny",
  "Shakira",
  "Karol G",
  "J Balvin",
  "Maluma",
  "Rosalia",
  "Anitta",
  "Rauw Alejandro",
  "Daddy Yankee",
  "Luis Fonsi",
  "Enrique Iglesias",
  "Ricky Martin",
  "Peso Pluma",
  "Natanael Cano",
  "BTS",
  "Blackpink",
  "Jungkook",
  "Jimin",
  "V",
  "RM",
  "Suga",
  "J-Hope",
  "Jin",
  "Lisa",
  "Jennie",
  "Rose",
  "Jisoo",
  "NewJeans",
  "Twice",
  "Stray Kids",
  "Seventeen",
  "EXO",
  "BigBang",
  "G-Dragon",
  "Psy",
  "IU",
  "Aespa",
  "Le Sserafim",
  "Itzy",
  "Babymetal",
  "Hikaru Utada",
  "Ayumi Hamasaki",
  "One Ok Rock",
  "Miyavi",
  "Jay Chou",
  "Jolin Tsai",
  "Jackson Wang",
  "Lay Zhang",
  "Jacky Cheung",
  "Faye Wong",
  "Teresa Teng",
  "Amitabh Bachchan",
  "Shah Rukh Khan",
  "Salman Khan",
  "Aamir Khan",
  "Priyanka Chopra",
  "Deepika Padukone",
  "Aishwarya Rai",
  "Diljit Dosanjh",
  "Burna Boy",
  "Wizkid",
  "Davido",
  "Tems",
  "Tyla",
] as const;

const aliases: Record<string, string[]> = {
  "ASAP Rocky": ["A$AP Rocky"],
  "Beyonce": ["Beyonce Knowles", "Queen Bey"],
  "Blackpink": ["BLACKPINK"],
  "Cardi B": ["Belcalis Almanzar"],
  "Celine Dion": ["Celine Dion"],
  "Cristiano Ronaldo": ["CR7", "Ronaldo 7", "Cristiano Ronaldo 7"],
  "David Beckham": ["Beckham 7"],
  "Dennis Rodman": ["Rodman", "Bulls 91", "Rodman 91", "Chicago Bulls 91"],
  "Dwayne Johnson": ["The Rock"],
  "Dwayne Wade": ["Dwyane Wade"],
  "Elvis Presley": ["The King Elvis"],
  "Eminem": ["Marshall Mathers", "Slim Shady"],
  "Freddie Mercury": ["Queen Freddie Mercury"],
  "Giannis Antetokounmpo": ["Greek Freak"],
  "Guns N Roses": ["Guns N' Roses"],
  "Jay-Z": ["Jay Z", "Shawn Carter"],
  "Jimi Hendrix": ["Hendrix"],
  "Kanye West": ["Ye", "Yeezy"],
  "Karim Benzema": ["Benzema 9"],
  "KISS": ["Kiss band"],
  "Kobe Bryant": ["Black Mamba", "Mamba", "Lakers 24", "Lakers 8", "Kobe 24"],
  "Kylian Mbappe": ["Mbappe 10"],
  "LeBron James": ["Lebron", "King James", "Lakers 23", "Cavs 23", "LeBron 23"],
  "Lionel Messi": ["Messi 10", "Leo Messi"],
  "Michael Jackson": ["MJ Michael Jackson"],
  "Michael Jordan": ["MJ 23", "Jordan 23", "Bulls 23", "Air Jordan"],
  "Neymar": ["Neymar Jr", "Neymar 10"],
  "Notorious B.I.G.": ["Biggie Smalls", "The Notorious BIG"],
  "Odell Beckham Jr.": ["OBJ"],
  "Pele": ["Edson Arantes do Nascimento"],
  "Prince": ["Prince Rogers Nelson"],
  "Rihanna": ["Robyn Rihanna Fenty"],
  "Ronaldo Nazario": ["R9"],
  "Shaquille O'Neal": ["Shaq"],
  "Snoop Dogg": ["Snoop Doggy Dogg"],
  "Stephen Curry": ["Steph Curry", "Curry 30", "Warriors 30"],
  "Taylor Swift": ["Swiftie", "Eras Tour"],
  "The Weeknd": ["Abel Tesfaye"],
  "Tupac Shakur": ["2Pac", "Tupac"],
  "Usain Bolt": ["Lightning Bolt"],
  "Ye": ["Kanye West", "Yeezy"],
  "Zinedine Zidane": ["Zidane 10"],
};

const imageHashes: Record<string, string> = {
  "Dennis Rodman": "1818087ebfbd3c26",
};

function uniqueNames(names: readonly string[]) {
  const seen = new Set<string>();
  return names.filter((name) => {
    const normalized = name.toLowerCase();
    if (seen.has(normalized)) return false;
    seen.add(normalized);
    return true;
  });
}

const groupedNames = [
  ...northAmericaMusic.map((name) => ({ name, region: "North America music" })),
  ...europeMusic.map((name) => ({ name, region: "Europe music" })),
  ...filmAndTelevision.map((name) => ({ name, region: "Film and television" })),
  ...sportsStars.map((name) => ({ name, region: "Sports" })),
  ...fashionAndCulture.map((name) => ({ name, region: "Fashion, art and public figures" })),
  ...globalMusicAndGroups.map((name) => ({ name, region: "Global music and entertainment" })),
];

export const celebrityReferenceSeeds: CelebrityReferenceSeed[] = uniqueNames(groupedNames.map((item) => item.name)).map(
  (name) => {
    const original = groupedNames.find((item) => item.name === name);
    return {
      aliases: aliases[name] ?? [],
      imageHash: imageHashes[name] ?? null,
      imageUrl: null,
      name,
      region: original?.region ?? "Global public figure",
    };
  },
);
