import type {
  InfringementRule,
  InfringementRuleCategory,
  InfringementRuleEntry,
  InfringementSeverity,
} from "@/lib/infringement/types";

export const RULE_ENGINE_VERSION = "2026-06-23-apparel-rule-v6";

const apparelContexts = [
  "t-shirt",
  "tshirt",
  "tee",
  "shirt",
  "hoodie",
  "sweatshirt",
  "crewneck",
  "tank top",
  "jersey",
  "cap",
  "hat",
  "bag",
  "tote bag",
  "mug",
  "sticker",
  "patch",
  "embroidery",
  "screen print",
  "dtf",
  "heat transfer",
  "vinyl decal",
  "svg",
  "png",
  "transparent png",
  "print file",
  "shirt design",
  "hoodie design",
  "graphic tee",
  "merch design",
  "apparel print",
  "服装印花",
  "衣服图案",
  "T恤印花",
  "短袖印花",
  "卫衣印花",
  "帽衫印花",
  "球衣图案",
  "烫画",
  "丝印",
  "热转印",
  "刺绣图案",
  "贴纸图案",
];

const riskyListingContexts = [
  "fan art",
  "fanart",
  "inspired",
  "inspired by",
  "parody",
  "parody of",
  "bootleg",
  "dupe",
  "replica",
  "fake",
  "counterfeit",
  "knockoff",
  "rip off",
  "same style",
  "look alike",
  "copy of",
  "unofficial",
  "official merch",
  "licensed merch",
  "limited edition",
  "collab",
  "collaboration",
  "粉丝作品",
  "致敬",
  "同款",
  "仿款",
  "复刻",
  "高仿",
  "山寨",
  "盗版",
  "非官方",
  "官方周边",
  "授权周边",
  "联名",
];

const visualMarkContexts = [
  "logo",
  "trademark",
  "registered mark",
  "brand mark",
  "monogram",
  "mascot",
  "emblem",
  "team logo",
  "club logo",
  "wordmark",
  "slogan",
  "商标",
  "标志",
  "品牌标识",
  "注册商标",
  "队标",
  "徽章",
  "吉祥物",
  "口号",
];

const entertainmentRoots = [
  "disney",
  "pixar",
  "marvel",
  "avengers",
  "spider-man",
  "spiderman",
  "iron man",
  "captain america",
  "hulk",
  "thor",
  "black panther",
  "deadpool",
  "x-men",
  "star wars",
  "darth vader",
  "yoda",
  "grogu",
  "mandalorian",
  "mickey mouse",
  "minnie mouse",
  "donald duck",
  "goofy",
  "stitch",
  "lilo and stitch",
  "frozen",
  "elsa",
  "olaf",
  "winnie the pooh",
  "toy story",
  "buzz lightyear",
  "pokemon",
  "pikachu",
  "nintendo",
  "mario",
  "luigi",
  "zelda",
  "animal crossing",
  "minecraft",
  "roblox",
  "fortnite",
  "sonic",
  "spongebob",
  "barbie",
  "the grinch",
  "simpsons",
  "stranger things",
  "star trek",
  "lord of the rings",
  "lotr",
  "hello kitty",
  "sanrio",
  "kuromi",
  "my melody",
  "harry potter",
  "hogwarts",
  "dc comics",
  "batman",
  "superman",
  "wonder woman",
  "joker",
  "one piece",
  "naruto",
  "dragon ball",
  "demon slayer",
  "snoopy",
  "peanuts",
  "sesame street",
  "care bears",
  "transformers",
  "minions",
  "despicable me",
  "jurassic park",
  "jurassic world",
  "game of thrones",
  "wednesday addams",
  "the addams family",
  "迪士尼",
  "皮克斯",
  "漫威",
  "复仇者联盟",
  "蜘蛛侠",
  "星球大战",
  "米奇",
  "米妮",
  "唐老鸭",
  "史迪奇",
  "冰雪奇缘",
  "艾莎",
  "小熊维尼",
  "宝可梦",
  "皮卡丘",
  "任天堂",
  "马里奥",
  "塞尔达",
  "我的世界",
  "海绵宝宝",
  "芭比",
  "哈利波特",
  "霍格沃茨",
  "蝙蝠侠",
  "超人",
  "海贼王",
  "火影忍者",
  "龙珠",
  "史努比",
  // 2026-06 扩充：动漫
  "attack on titan",
  "jujutsu kaisen",
  "my hero academia",
  "sailor moon",
  "studio ghibli",
  "totoro",
  "spirited away",
  "chainsaw man",
  "one punch man",
  "jojo's bizarre adventure",
  "neon genesis evangelion",
  "gundam",
  "doraemon",
  "tokyo ghoul",
  "hunter x hunter",
  "crayon shin-chan",
  "detective conan",
  // 2026-06 扩充：卡通 / 影视 IP
  "peppa pig",
  "powerpuff girls",
  "looney tunes",
  "bugs bunny",
  "tom and jerry",
  "rick and morty",
  "squid game",
  "paw patrol",
  "scooby doo",
  "south park",
  "family guy",
  "kung fu panda",
  "shrek",
  // 2026-06 扩充：游戏 IP
  "genshin impact",
  "league of legends",
  "valorant",
  "overwatch",
  "call of duty",
  "among us",
  "elden ring",
  // 2026-06 扩充：中文别名
  "进击的巨人",
  "咒术回战",
  "我的英雄学院",
  "美少女战士",
  "吉卜力",
  "龙猫",
  "千与千寻",
  "电锯人",
  "一拳超人",
  "新世纪福音战士",
  "高达",
  "哆啦a梦",
  "机器猫",
  "蜡笔小新",
  "名侦探柯南",
  "小猪佩奇",
  "飞天小女警",
  "瑞克和莫蒂",
  "鱿鱼游戏",
  "汪汪队",
  "猫和老鼠",
  "功夫熊猫",
  "原神",
  "英雄联盟",
  "守望先锋",
  "使命召唤",
];

const brandRoots = [
  "nike",
  "air jordan",
  "jordan",
  "adidas",
  "puma",
  "reebok",
  "new balance",
  "converse",
  "vans",
  "supreme",
  "off white",
  "off-white",
  "yeezy",
  "gucci",
  "louis vuitton",
  "lv monogram",
  "chanel",
  "dior",
  "prada",
  "versace",
  "balenciaga",
  "burberry",
  "hermes",
  "rolex",
  "cartier",
  "playboy",
  "starbucks",
  "coca cola",
  "coca-cola",
  "pepsi",
  "mcdonald",
  "mcdonalds",
  "apple logo",
  "apple inc",
  "tesla",
  "harley-davidson",
  "harley davidson",
  "red bull",
  "monster energy",
  "jack daniels",
  "budweiser",
  "heineken",
  "hennessy",
  "jagermeister",
  "patagonia",
  "the north face",
  "columbia sportswear",
  "under armour",
  "lululemon",
  "crocs",
  "timberland",
  "dr martens",
  "doc martens",
  "playstation",
  "xbox",
  "netflix",
  "youtube",
  "tiktok",
  "instagram",
  "facebook",
  "meta",
  "耐克",
  "乔丹",
  "阿迪达斯",
  "彪马",
  "锐步",
  "新百伦",
  "匡威",
  "万斯",
  "古驰",
  "路易威登",
  "香奈儿",
  "迪奥",
  "普拉达",
  "范思哲",
  "巴黎世家",
  "巴宝莉",
  "爱马仕",
  "劳力士",
  "卡地亚",
  "星巴克",
  "可口可乐",
  "百事",
  "麦当劳",
  "苹果标志",
  "特斯拉",
  "哈雷",
  "红牛",
  "怪兽能量",
  // 2026-06 扩充：汽车品牌
  "ferrari",
  "lamborghini",
  "porsche",
  "bmw",
  "mercedes-benz",
  "mercedes benz",
  "bugatti",
  "audi",
  "bentley",
  "rolls royce",
  "rolls-royce",
  "maserati",
  "mclaren",
  // 2026-06 扩充：潮牌 / 街头
  "stussy",
  "stüssy",
  "bape",
  "a bathing ape",
  "fear of god",
  "kith",
  "anti social social club",
  "kaws",
  "thrasher",
  "palace skateboards",
  "stone island",
  "fila",
  "moncler",
  // 2026-06 扩充：奢侈品
  "fendi",
  "givenchy",
  "saint laurent",
  "ysl",
  "celine",
  "loewe",
  "bottega veneta",
  "valentino",
  // 2026-06 扩充：其他 / 中文别名
  "lego",
  "法拉利",
  "兰博基尼",
  "保时捷",
  "宝马",
  "奔驰",
  "布加迪",
  "奥迪",
  "宾利",
  "劳斯莱斯",
  "玛莎拉蒂",
  "芬迪",
  "纪梵希",
  "圣罗兰",
  "乐高",
  "斐乐",
];

const sportsRoots = [
  "nba",
  "nfl",
  "mlb",
  "nhl",
  "fifa",
  "olympics",
  "olympic games",
  "uefa",
  "champions league",
  "world cup",
  "super bowl",
  "formula 1",
  "f1",
  "chicago bulls",
  "lakers",
  "warriors",
  "bulls",
  "celtics",
  "yankees",
  "dodgers",
  "cowboys",
  "patriots",
  "chiefs",
  "packers",
  "manchester united",
  "man united",
  "real madrid",
  "barcelona fc",
  "arsenal",
  "chelsea",
  "liverpool",
  "psg",
  "bayern munich",
  "juventus",
  "inter milan",
  "ac milan",
  "湖人",
  "勇士",
  "芝加哥公牛",
  "公牛",
  "凯尔特人",
  "洋基",
  "道奇",
  "曼联",
  "皇马",
  "巴萨",
  "阿森纳",
  "切尔西",
  "利物浦",
  "巴黎圣日耳曼",
  "拜仁",
  "世界杯",
  "奥运",
  "欧冠",
  "超级碗",
];

const celebrityRoots = [
  "taylor swift",
  "beyonce",
  "rihanna",
  "bts",
  "blackpink",
  "bad bunny",
  "billie eilish",
  "ariana grande",
  "justin bieber",
  "selena gomez",
  "kobe bryant",
  "lebron james",
  "michael jordan",
  "dennis rodman",
  "rodman",
  "lionel messi",
  "cristiano ronaldo",
  "ronaldo",
  "neymar",
  "mbappe",
  "elon musk",
  "donald trump",
  "joe biden",
  "obama",
  "marilyn monroe",
  "elvis presley",
  "the beatles",
  "nirvana",
  "rolling stones",
  "metallica",
  "acdc",
  "ac/dc",
  "queen band",
  "泰勒斯威夫特",
  "碧昂丝",
  "蕾哈娜",
  "贾斯汀比伯",
  "赛琳娜",
  "科比",
  "詹姆斯",
  "迈克尔乔丹",
  "丹尼斯罗德曼",
  "罗德曼",
  "梅西",
  "C罗",
  "内马尔",
  "姆巴佩",
  "马斯克",
  "特朗普",
  "奥巴马",
];

const copyrightWorkRoots = [
  "movie poster",
  "album cover",
  "book cover",
  "comic cover",
  "anime screenshot",
  "game screenshot",
  "tv show screenshot",
  "meme character",
  "cartoon character",
  "licensed character",
  "copyrighted artwork",
  "stock photo watermark",
  "shutterstock",
  "getty images",
  "alamy",
  "adobe stock",
  "电影海报",
  "专辑封面",
  "书籍封面",
  "漫画封面",
  "动漫截图",
  "游戏截图",
  "影视截图",
  "卡通角色",
  "受版权保护作品",
  "素材水印",
];

const supplementalEntertainmentRoots = [
  "bluey",
  "cocomelon",
  "baby shark",
  "pj masks",
  "blues clues",
  "miffy",
  "pusheen",
  "rilakkuma",
  "cinnamoroll",
  "pochacco",
  "keroppi",
  "gudetama",
  "bratz",
  "squishmallows",
  "my little pony",
  "power rangers",
  "teenage mutant ninja turtles",
  "tmnt",
  "garfield",
  "smurfs",
  "calvin and hobbes",
  "dr seuss",
  "cat in the hat",
  "labubu",
  "pop mart",
  "sonny angel",
  "betty boop",
  "popeye",
  "the flintstones",
  "the jetsons",
  "adventure time",
  "steven universe",
  "gravity falls",
  "hazbin hotel",
  "helluva boss",
  "kirby",
  "yoshi",
  "donkey kong",
  "metroid",
  "pac-man",
  "pacman",
  "tetris",
  "halo",
  "world of warcraft",
  "diablo",
  "final fantasy",
  "kingdom hearts",
  "persona 5",
  "resident evil",
  "street fighter",
  "mortal kombat",
  "tekken",
  "hatsune miku",
  "vocaloid",
  "bleach anime",
  "death note",
  "fullmetal alchemist",
  "spy x family",
  "haikyuu",
  "blue lock",
  "tokyo revengers",
  "solo leveling",
  "frieren",
  "boruto",
  "naruto shippuden",
  "sailor moon crystal",
];

const supplementalBrandRoots = [
  "chrome hearts",
  "gallery dept",
  "essentials fear of god",
  "ralph lauren",
  "polo ralph lauren",
  "polo bear",
  "lacoste",
  "tommy hilfiger",
  "calvin klein",
  "carhartt",
  "champion",
  "oakley",
  "new era",
  "crocs jibbitz",
  "dr pepper",
  "sprite",
  "mountain dew",
  "fanta",
  "7-eleven",
  "dunkin",
  "kfc",
  "burger king",
  "dominos",
  "taco bell",
  "walmart",
  "target logo",
  "costco",
  "stanley cup",
  "yeti cooler",
  "hydro flask",
  "hot wheels",
  "monster jam",
  "nascar",
  "john deere",
  "caterpillar",
  "cat equipment",
  "deere logo",
  "nasa worm logo",
  "nasa meatball logo",
  "fbi seal",
  "cia seal",
  "usps logo",
  "fedex logo",
  "ups logo",
];

const supplementalSportsRoots = [
  "miami heat",
  "new york knicks",
  "brooklyn nets",
  "philadelphia 76ers",
  "sixers",
  "phoenix suns",
  "dallas mavericks",
  "denver nuggets",
  "milwaukee bucks",
  "miami dolphins",
  "philadelphia eagles",
  "san francisco 49ers",
  "new york giants",
  "new york jets",
  "buffalo bills",
  "seattle seahawks",
  "las vegas raiders",
  "pittsburgh steelers",
  "boston red sox",
  "new york mets",
  "atlanta braves",
  "chicago cubs",
  "houston astros",
  "san francisco giants",
  "toronto blue jays",
  "boston bruins",
  "toronto maple leafs",
  "new york rangers",
  "vegas golden knights",
  "ufc",
  "wwe",
  "wrestlemania",
  "nascar cup series",
  "formula one",
  "motogp",
  "premier league",
  "la liga",
  "serie a",
  "bundesliga",
  "uefa euro",
  "copa america",
];

const supplementalCelebrityRoots = [
  "lady gaga",
  "madonna",
  "olivia rodrigo",
  "sabrina carpenter",
  "doja cat",
  "nicki minaj",
  "cardi b",
  "lana del rey",
  "katy perry",
  "michael jackson",
  "johnny cash",
  "dolly parton",
  "jimi hendrix",
  "kurt cobain",
  "guns n roses",
  "red hot chili peppers",
  "linkin park",
  "dua lipa",
  "adele",
  "harry styles",
  "ed sheeran",
  "david bowie",
  "freddie mercury",
  "pink floyd",
  "led zeppelin",
  "oasis",
  "coldplay",
  "spice girls",
  "tom cruise",
  "leonardo dicaprio",
  "johnny depp",
  "keanu reeves",
  "dwayne johnson",
  "will smith",
  "tom brady",
  "patrick mahomes",
  "stephen curry",
  "shaquille o'neal",
  "serena williams",
  "venus williams",
  "tiger woods",
  "conor mcgregor",
  "muhammad ali",
  "mike tyson",
];

const supplementalCopyrightWorkRoots = [
  "movie still",
  "screen capture",
  "screencap",
  "anime panel",
  "manga panel",
  "comic panel",
  "album art",
  "record cover",
  "poster art",
  "character vector",
  "character png",
  "cartoon svg",
  "anime png",
  "game sprite",
  "sprite sheet",
  "official poster",
  "unlicensed fan art",
  "bootleg merch",
  "not official",
  "inspired merch",
  "parody shirt",
  "lookalike logo",
  "replica logo",
  "logo redraw",
  "brand parody",
  "trademark parody",
  "watermarked stock",
  "getty watermark",
  "shutterstock watermark",
  "alamy watermark",
  "adobe stock watermark",
];

const supplementalLogoContexts = [
  "crest",
  "badge",
  "shield logo",
  "sports crest",
  "team crest",
  "luxury monogram",
  "monogram pattern",
  "swoosh",
  "three stripes",
  "jumpman",
  "interlocking cc",
  "lv pattern",
  "burberry check",
  "polo horse",
  "crocodile logo",
  "bullseye logo",
  "mascot head",
  "emblem patch",
  "seal logo",
];

function normalizeTerm(term: string) {
  return term.toLowerCase().replace(/\s+/g, " ").trim();
}

function dedupeTerms(terms: string[]) {
  const seen = new Set<string>();
  const result: string[] = [];

  for (const term of terms) {
    const normalized = normalizeTerm(term);
    if (!normalized || seen.has(normalized)) continue;
    seen.add(normalized);
    result.push(term.trim());
  }

  return result;
}

function expandWithContexts(roots: string[], contexts: string[]) {
  return roots.flatMap((root) => contexts.map((context) => `${root} ${context}`));
}

function buildProtectedTerms(roots: string[], extraContexts: string[] = []) {
  return dedupeTerms([
    ...roots,
    ...expandWithContexts(roots, apparelContexts),
    ...expandWithContexts(roots, riskyListingContexts),
    ...expandWithContexts(roots, visualMarkContexts),
    ...expandWithContexts(roots, extraContexts),
  ]);
}

function createRuleEntry(rule: InfringementRule, term: string, index: number): InfringementRuleEntry {
  return {
    category: rule.category,
    descriptionEn: rule.descriptionEn,
    descriptionZh: rule.descriptionZh,
    id: `${rule.id}-${index + 1}`,
    labelEn: rule.labelEn,
    labelZh: rule.labelZh,
    policyBasisEn: rule.policyBasisEn,
    policyBasisZh: rule.policyBasisZh,
    ruleId: rule.id,
    severity: rule.severity,
    sourceLabel: rule.sourceLabel,
    sourceUrl: rule.sourceUrl,
    term,
  };
}

export const infringementRules: InfringementRule[] = [
  {
    category: "character",
    descriptionEn: "Major entertainment franchises and protected characters should not be used for POD unless licensed.",
    descriptionZh: "影视、动漫、游戏 IP 和受保护角色通常不能直接用于服装印花或 POD 商品，除非已有明确授权。",
    id: "entertainment-franchise-apparel",
    labelEn: "Entertainment franchise / character",
    labelZh: "影视动漫游戏 IP / 角色",
    policyBasisEn: "Character art, franchise names and derivative fan merchandise require rights clearance before sale.",
    policyBasisZh: "角色图、影视游戏名称和粉丝衍生周边在商用前需要确认版权、商标或授权。",
    severity: "critical",
    sourceLabel: "Printful Content Guidelines",
    sourceUrl: "https://www.printful.com/policies/content-guidelines",
    terms: buildProtectedTerms([...entertainmentRoots, ...supplementalEntertainmentRoots]),
  },
  {
    category: "brand",
    descriptionEn: "Famous brand names and marks generally require authorization for apparel and merchandise.",
    descriptionZh: "知名品牌名称、商标、字标和视觉识别用于衣服图案或商品通常需要授权。",
    id: "famous-brand-apparel",
    labelEn: "Famous brand / trademark",
    labelZh: "知名品牌 / 商标",
    policyBasisEn: "Brand names, logos and product identifiers can be trademarks when used on goods or listing copy.",
    policyBasisZh: "品牌名、Logo、字标、花押图案和商品识别元素用于服装或上架文案时可能构成商标风险。",
    severity: "critical",
    sourceLabel: "USPTO Trademark Basics",
    sourceUrl: "https://www.uspto.gov/trademarks/basics",
    terms: buildProtectedTerms([...brandRoots, ...supplementalBrandRoots]),
  },
  {
    category: "sports",
    descriptionEn: "Team, league and event names or logos are usually licensed for apparel and POD products.",
    descriptionZh: "球队、联盟、赛事名称或 Logo 用于服饰、球衣和 POD 商品通常需要授权。",
    id: "sports-league-team-apparel",
    labelEn: "Sports league / team mark",
    labelZh: "体育联盟 / 球队标识",
    policyBasisEn: "Sports league, team and event marks are frequently protected for apparel categories.",
    policyBasisZh: "体育联盟、球队和赛事标识在服装类目中通常是重点授权内容，球衣场景尤其高风险。",
    severity: "high",
    sourceLabel: "USPTO Trademark Basics",
    sourceUrl: "https://www.uspto.gov/trademarks/basics",
    terms: buildProtectedTerms(
      [...sportsRoots, ...supplementalSportsRoots],
      ["jersey number", "championship shirt", "team jersey"],
    ),
  },
  {
    category: "celebrity",
    descriptionEn: "Celebrity names, portraits, bands and personal likeness can create publicity-right or trademark risk.",
    descriptionZh: "名人姓名、肖像、乐队名称和公众形象可能涉及肖像权、姓名权、版权或商标风险。",
    id: "celebrity-publicity-right-apparel",
    labelEn: "Celebrity / publicity right",
    labelZh: "名人 / 肖像姓名权",
    policyBasisEn: "People, bands and athlete likenesses need manual review before commercial apparel use.",
    policyBasisZh: "人物、乐队和运动员相关图文用于服装印花前需要人工确认授权与平台规则。",
    severity: "high",
    sourceLabel: "Printify Intellectual Property Policy",
    sourceUrl: "https://printify.com/intellectual-property-policy/",
    terms: buildProtectedTerms(
      [...celebrityRoots, ...supplementalCelebrityRoots],
      ["portrait", "face", "tour shirt", "concert tee", "memorial shirt"],
    ),
  },
  {
    category: "copyright_phrase",
    descriptionEn: "Phrases like fan art or inspired by are not safe by themselves and should trigger manual review.",
    descriptionZh: "“粉丝作品、致敬、同款、复刻、非官方”等表述不能自动规避风险，应进入人工复核。",
    id: "derivative-work-apparel-phrases",
    labelEn: "Derivative-work phrase",
    labelZh: "衍生作品风险表述",
    policyBasisEn: "Marketplace wording that implies copying, fan art or unauthorized licensing should be reviewed before export.",
    policyBasisZh: "暗示仿制、粉丝衍生、非官方授权或联名的文案在导出前需要确认来源和授权。",
    severity: "medium",
    sourceLabel: "Etsy Intellectual Property Policy",
    sourceUrl: "https://www.etsy.com/legal/ip/",
    terms: dedupeTerms([
      ...riskyListingContexts,
      ...visualMarkContexts,
      ...copyrightWorkRoots,
      ...supplementalCopyrightWorkRoots,
      ...expandWithContexts(riskyListingContexts, apparelContexts),
      ...expandWithContexts(supplementalCopyrightWorkRoots, apparelContexts),
      "official merchandise",
      "licensed merchandise",
      "brand collaboration",
      "授权商品",
      "正版周边",
      "联名款",
      "限量款",
      "商业授权素材",
    ]),
  },
  {
    category: "logo",
    descriptionEn: "Requests or file names mentioning logos need human review unless the logo is owned by the seller.",
    descriptionZh: "文件名或商品信息出现 Logo、商标、队标、徽章、吉祥物等词时，需要确认是否自有或已授权。",
    id: "logo-or-trademark-apparel-mention",
    labelEn: "Logo / trademark mention",
    labelZh: "Logo / 商标提及",
    policyBasisEn: "Logo extraction or logo-like artwork is sensitive for POD because it can be applied directly to goods.",
    policyBasisZh: "POD 印花会直接把图案用于商品，因此 Logo 提取、队标、徽章和字标需要人工复核。",
    severity: "medium",
    sourceLabel: "Amazon Brand Registry",
    sourceUrl: "https://sell.amazon.com/brand-registry/",
    terms: dedupeTerms([
      ...visualMarkContexts,
      ...supplementalLogoContexts,
      ...expandWithContexts(visualMarkContexts, apparelContexts),
      ...expandWithContexts(supplementalLogoContexts, apparelContexts),
    ]),
  },
  {
    category: "marketplace",
    descriptionEn: "Marketplace listing terms often used by infringing POD sellers should trigger review before export.",
    descriptionZh: "部分上架词常见于侵权周边，导出前应复核素材来源、授权文件和商品文案。",
    id: "marketplace-risk-apparel-copy",
    labelEn: "Marketplace risk copy",
    labelZh: "平台上架风险文案",
    policyBasisEn: "Listing claims such as official, licensed or authentic should only be used with evidence.",
    policyBasisZh: "官方、授权、正版、联名、限量等上架表述必须有证据支持，否则容易触发平台审核。",
    severity: "low",
    sourceLabel: "Amazon Report a Violation",
    sourceUrl: "https://sell.amazon.com/blog/report-a-violation-to-amazon",
    terms: dedupeTerms([
      "official merch",
      "official merchandise",
      "licensed merch",
      "licensed merchandise",
      "authentic",
      "limited edition",
      "collab",
      "collaboration",
      "brand collaboration",
      "授权周边",
      "官方周边",
      "正版",
      "联名",
      "限定款",
      "合作款",
      ...expandWithContexts(["official", "licensed", "authentic", "limited edition", "collab"], apparelContexts),
    ]),
  },
];

export const infringementRuleEntries: InfringementRuleEntry[] = infringementRules.flatMap((rule) =>
  rule.terms.map((term, index) => createRuleEntry(rule, term, index)),
);

function createEmptyCategoryStats() {
  return {
    brand: 0,
    celebrity: 0,
    character: 0,
    copyright_phrase: 0,
    logo: 0,
    marketplace: 0,
    sports: 0,
    visual_review: 0,
  } satisfies Record<InfringementRuleCategory, number>;
}

function createEmptySeverityStats() {
  return {
    critical: 0,
    high: 0,
    low: 0,
    medium: 0,
  } satisfies Record<InfringementSeverity, number>;
}

export const infringementRuleStats = infringementRuleEntries.reduce(
  (stats, entry) => {
    stats.byCategory[entry.category] += 1;
    stats.bySeverity[entry.severity] += 1;
    return stats;
  },
  {
    byCategory: createEmptyCategoryStats(),
    bySeverity: createEmptySeverityStats(),
    sourceCount: new Set(infringementRules.map((rule) => rule.sourceUrl).filter(Boolean)).size,
    totalRules: infringementRules.length,
    totalTerms: infringementRuleEntries.length,
    version: RULE_ENGINE_VERSION,
  },
);
