import type { InfringementRule } from "@/lib/infringement/types";

export const RULE_ENGINE_VERSION = "2026-06-03-rule-v2";

export const infringementRules: InfringementRule[] = [
  {
    category: "character",
    descriptionEn: "Major entertainment franchises and protected characters should not be used for POD unless licensed.",
    descriptionZh: "影视、动漫、游戏 IP 和受保护角色通常不能直接用于 POD，除非已有授权。",
    id: "entertainment-franchise-core",
    labelEn: "Entertainment franchise / character",
    labelZh: "影视动漫游戏 IP / 角色",
    severity: "critical",
    terms: [
      "disney",
      "pixar",
      "marvel",
      "avengers",
      "spider-man",
      "spiderman",
      "star wars",
      "mickey mouse",
      "minnie mouse",
      "donald duck",
      "stitch",
      "lilo and stitch",
      "frozen",
      "elsa",
      "winnie the pooh",
      "pokemon",
      "pokémon",
      "pikachu",
      "nintendo",
      "mario",
      "zelda",
      "animal crossing",
      "minecraft",
      "roblox",
      "fortnite",
      "sonic",
      "spongebob",
      "barbie",
      "the grinch",
      "simpsons",
      "stranger things",
      "star trek",
      "lord of the rings",
      "lotr",
      "hello kitty",
      "sanrio",
      "harry potter",
      "hogwarts",
      "dc comics",
      "batman",
      "superman",
      "one piece",
      "naruto",
      "dragon ball",
      "snoopy",
      "peanuts",
      "迪士尼",
      "皮克斯",
      "漫威",
      "复仇者联盟",
      "蜘蛛侠",
      "星球大战",
      "米奇",
      "米妮",
      "唐老鸭",
      "史迪奇",
      "冰雪奇缘",
      "艾莎",
      "小熊维尼",
      "宝可梦",
      "皮卡丘",
      "任天堂",
      "马里奥",
      "塞尔达",
      "动物森友会",
      "我的世界",
      "堡垒之夜",
      "索尼克",
      "海绵宝宝",
      "芭比",
      "格林奇",
      "辛普森",
      "怪奇物语",
      "星际迷航",
      "指环王",
      "三丽鸥",
      "凯蒂猫",
      "哈利波特",
      "霍格沃茨",
      "蝙蝠侠",
      "超人",
      "海贼王",
      "火影忍者",
      "龙珠",
      "史努比",
    ],
  },
  {
    category: "brand",
    descriptionEn: "Famous brand names and marks generally require authorization for merchandise.",
    descriptionZh: "知名品牌名称、商标和视觉识别通常需要授权才能用于商品。",
    id: "famous-brand-core",
    labelEn: "Famous brand / trademark",
    labelZh: "知名品牌 / 商标",
    severity: "critical",
    terms: [
      "nike",
      "air jordan",
      "jordan",
      "adidas",
      "puma",
      "reebok",
      "supreme",
      "off white",
      "off-white",
      "yeezy",
      "gucci",
      "louis vuitton",
      "lv monogram",
      "chanel",
      "dior",
      "prada",
      "versace",
      "balenciaga",
      "burberry",
      "hermes",
      "hermès",
      "rolex",
      "cartier",
      "playboy",
      "starbucks",
      "coca cola",
      "coca-cola",
      "pepsi",
      "mcdonald",
      "mcdonalds",
      "apple logo",
      "tesla",
      "harley-davidson",
      "harley davidson",
      "耐克",
      "乔丹",
      "阿迪达斯",
      "彪马",
      "锐步",
      "supreme",
      "椰子鞋",
      "off white",
      "古驰",
      "路易威登",
      "香奈儿",
      "迪奥",
      "普拉达",
      "范思哲",
      "巴黎世家",
      "巴宝莉",
      "爱马仕",
      "劳力士",
      "卡地亚",
      "花花公子",
      "星巴克",
      "可口可乐",
      "百事",
      "麦当劳",
      "苹果标志",
      "特斯拉",
      "哈雷",
    ],
  },
  {
    category: "sports",
    descriptionEn: "Team, league and event names or logos are usually licensed for apparel and POD products.",
    descriptionZh: "球队、联盟、赛事名称或 Logo 用于服饰 / POD 商品通常需要授权。",
    id: "sports-league-team",
    labelEn: "Sports league / team mark",
    labelZh: "体育联盟 / 球队标识",
    severity: "high",
    terms: [
      "nba",
      "nfl",
      "mlb",
      "nhl",
      "fifa",
      "olympics",
      "uefa",
      "champions league",
      "world cup",
      "super bowl",
      "lakers",
      "warriors",
      "bulls",
      "celtics",
      "yankees",
      "dodgers",
      "manchester united",
      "real madrid",
      "barcelona fc",
      "arsenal",
      "chelsea",
      "liverpool",
      "psg",
      "bayern munich",
      "湖人",
      "勇士",
      "公牛",
      "凯尔特人",
      "洋基",
      "道奇",
      "曼联",
      "皇马",
      "巴萨",
      "阿森纳",
      "切尔西",
      "利物浦",
      "巴黎圣日耳曼",
      "拜仁",
      "世界杯",
      "奥运",
      "欧冠",
      "超级碗",
    ],
  },
  {
    category: "celebrity",
    descriptionEn: "Celebrity names, portraits, bands and personal likeness can create publicity-right or trademark risk.",
    descriptionZh: "名人姓名、肖像、组合名称和公众形象可能涉及肖像权、姓名权或商标风险。",
    id: "celebrity-publicity-right",
    labelEn: "Celebrity / publicity right",
    labelZh: "名人 / 肖像姓名权",
    severity: "high",
    terms: [
      "taylor swift",
      "beyonce",
      "beyoncé",
      "rihanna",
      "bts",
      "blackpink",
      "bad bunny",
      "billie eilish",
      "ariana grande",
      "justin bieber",
      "selena gomez",
      "kobe bryant",
      "lebron james",
      "michael jordan",
      "lionel messi",
      "cristiano ronaldo",
      "neymar",
      "mbappe",
      "elon musk",
      "特朗普",
      "泰勒斯威夫特",
      "碧昂丝",
      "蕾哈娜",
      "贾斯汀比伯",
      "赛琳娜",
      "科比",
      "詹姆斯",
      "迈克尔乔丹",
      "梅西",
      "C罗",
      "内马尔",
      "姆巴佩",
      "马斯克",
    ],
  },
  {
    category: "copyright_phrase",
    descriptionEn: "Phrases like fan art or inspired by are not safe by themselves and should trigger manual review.",
    descriptionZh: "“粉丝作品 / 同款 / 致敬”等表述不能自动规避风险，应进入人工复核。",
    id: "derivative-work-phrases",
    labelEn: "Derivative-work phrase",
    labelZh: "衍生作品风险表述",
    severity: "medium",
    terms: [
      "fan art",
      "fanart",
      "inspired by",
      "parody of",
      "bootleg",
      "dupe",
      "replica",
      "fake",
      "counterfeit",
      "knockoff",
      "rip off",
      "rip-off",
      "same as",
      "look alike",
      "copy of",
      "unofficial",
      "粉丝作品",
      "饭制",
      "致敬",
      "同款",
      "仿牌",
      "仿款",
      "仿制",
      "山寨",
      "复刻",
      "高仿",
      "假货",
      "盗版",
      "平替",
      "非官方",
      "周边",
    ],
  },
  {
    category: "logo",
    descriptionEn: "Requests or file names mentioning logos need human review unless the logo is owned by the seller.",
    descriptionZh: "文件名或商品信息中出现 Logo / 商标相关词时，需要确认该标识是否自有或授权。",
    id: "logo-or-trademark-mention",
    labelEn: "Logo / trademark mention",
    labelZh: "Logo / 商标提及",
    severity: "medium",
    terms: [
      "logo",
      "trademark",
      "registered mark",
      "brand mark",
      "swoosh",
      "monogram",
      "emblem",
      "mascot",
      "team logo",
      "club logo",
      "标志",
      "商标",
      "注册商标",
      "品牌标识",
      "勾标",
      "花押字",
      "队标",
      "徽章",
      "吉祥物",
    ],
  },
  {
    category: "marketplace",
    descriptionEn: "Marketplace listing terms often used by infringing POD sellers should trigger review before export.",
    descriptionZh: "部分上架词常见于侵权周边，进入导出前应复核素材来源和授权。",
    id: "marketplace-risk-copy",
    labelEn: "Marketplace risk copy",
    labelZh: "平台上架风险文案",
    severity: "low",
    terms: [
      "official merch",
      "official merchandise",
      "licensed merch",
      "licensed merchandise",
      "authentic",
      "limited edition",
      "collab",
      "collaboration",
      "brand collaboration",
      "授权周边",
      "官方周边",
      "正版",
      "联名",
      "限定款",
      "合作款",
    ],
  },
];
